apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: calculator-ratelimit
    descriptors:
      - key: PATH
        value: "/calc"
        rate_limit:
          unit: minute
          requests_per_unit: 100
      # - key: PATH
      #   rate_limit:
      #     unit: minute
      #     requests_per_unit: 100
